apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample2
  namespace: application-service-system
spec:
  replicas: 2
  selector: null
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: FOO2
          value: BAR2
        image: quay.io/redhat-appstudio/user-workload:application-service-system-component-sample2
        name: container-image
        resources: {}
status: {}
